export const DEFAULT_OPTIONS = {
  prevLabel: 'Previous',
  nextLabel: 'Next',
  pauseLabel: 'Pause',
  resumeLabel: 'Resume',
  transitionSpeed: 600,
  scaleOnHover: 1.1,
  autoPlay: true,
  interval: 3000,
  shouldLoop: true,
  showArrows: true,
  selectedItem: 0,
  minHeight: '500px',
  showIndicators: true,
  dotIndicatorsSize: 28,
};
